# Generated by Django 3.2.4 on 2021-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Featured_Image', models.ImageField(upload_to='Blog_Images')),
                ('Title', models.CharField(max_length=2000)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Gallery_Images')),
                ('Alt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Programme_Images')),
                ('Short_Detail', models.TextField()),
                ('Full_Detail', models.TextField()),
                ('Type', models.CharField(choices=[('Donation', 'Donation'), ('Volunteer', 'Volunteer')], max_length=50)),
                ('Money_to_raise', models.FloatField()),
                ('Raised_till_now', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Volunteer_Images')),
                ('Position', models.CharField(max_length=100)),
                ('About', models.TextField()),
                ('Facebook', models.URLField(max_length=2000)),
                ('Twitter', models.URLField(max_length=2000)),
                ('Instagram', models.URLField(max_length=2000)),
            ],
        ),
    ]
