# Generated by Django 3.2.4 on 2021-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0002_alter_programme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='Money_to_raise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Raised_till_now',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
