# Generated by Django 3.2.4 on 2021-06-25 05:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0003_auto_20210624_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Full_Detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
